#!/usr/bin/python3
# Copyright 2020 Harish Krupo
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from xdg.BaseDirectory import (
    load_first_config,
    save_state_path
)

import argparse
import webbrowser
import logging
import json
import msal

from http.server import HTTPServer, BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs, urlencode
from wsgiref import simple_server
import wsgiref.util
import sys
import uuid
import pprint
import os
import atexit
import base64
import gnupg
import ssl
import io

pp = pprint.PrettyPrinter(indent=4)

APP_NAME = "oauth2ms"
SUCCESS_MESSAGE = "Authorization complete."
credentials_file = save_state_path("oauth2ms") + "/token.gpg"

_LOGGER = logging.getLogger(__name__)

parser = argparse.ArgumentParser()
parser.add_argument("--encode-xoauth2", action="store_true", default=False,
                    help="Print xoauth2 encoded token instead of the plain token")
parser.add_argument("-e", "--encrypt-using-fingerprint", action="store", default=None,
                    help="Use gpg encryption to encrypt/decrypt the token cache. Argument is the fingerprint/email to be used")
parser.add_argument("--gpg-home", action="store", default=None,
                    help="Set the gpg home directory")
parser.add_argument("--no-browser", action="store_true", default=False,
                    help="Don't open a browser with URL. Instead print the URL. Useful inside virtualized environments like WSL.")


def load_config():
    config_file = load_first_config(APP_NAME, "config.json")
    if config_file is None:
        _LOGGER.error(f"Couldn't find configuration file. Config file must be at: $XDG_CONFIG_HOME/{APP_NAME}/config.json")
        _LOGGER.info(f"Current value of $XDG_CONFIG_HOME is: {os.getenv("XDG_CONFIG_HOME")}")
        sys.exit(1)

    config = json.load(open(config_file, 'r'))
    if errs := validate_config(config):
        _LOGGER.error(f"Invalid config: {errs}")
        sys.exit(2)

    return config

def build_msal_app(config, cache = None):
    tenant = config.get('tenant_id')
    secret = config.get('client_secret')
    cache = cache or msal.SerializableTokenCache()
    return msal.ConfidentialClientApplication(
        config['client_id'],
        authority=("https://login.microsoftonline.com/" + tenant + "/" if tenant else None),
        client_credential=secret,
        token_cache=cache
    ), cache

def ssl_context(certf="cert.pem", keyf="key.pem"):
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(certf, keyf)
    return context

class WSGIRequestHandler(wsgiref.simple_server.WSGIRequestHandler):
    """Silence out the messages from the http server"""
    def log_message(self, format, *args):
        pass

class WSGIRedirectionApp(object):
    """WSGI app to handle the authorization redirect.

    Stores the request URI and displays the given success message.
    """

    def __init__(self, message):
        self.last_request_uri = None
        self._success_message = message

    def __call__(self, environ, start_response):
        start_response("200 OK", [("Content-type", "text/plain; charset=utf-8")])
        self.last_request_uri = wsgiref.util.request_uri(environ)
        return [self._success_message.encode("utf-8")]

def validate_config(config):
    errs = {}

    # Make sure tenant_id is a string when present
    if "tenant_id" in config and not isinstance(config["tenant_id"], str):
        errs["tenant_id"] = "Must be a string when present in config"

    # Make sure client_id is present and is a string
    if "client_id" not in config:
        errs["client_id"] = "Mandatory string field"
    elif not isinstance(config["client_id"], str):
        errs["client_id"] = "Not a valid string"

    # Make sure client_secret is a string when present
    if "client_secret" in config and not isinstance(config["client_secret"], str):
        errs["client_secret"] = "Must be a string when present in config"

    # Make sure scopes is present and is a list of strings
    if "scopes" not in config:
        errs["scopes"] = "Missing required field"
    elif not isinstance(config["scopes"], list):
        errs["scopes"] = "Not a valid list"

    scopes_errs = {}
    for i, datum in enumerate(config["scopes"]):
        if not isinstance(datum, str):
            scopes_errs[i] = "Not a valid string"

    if scopes_errs:
        errs["scopes"] = scopes_errs

    # Make sure redirect is present
    if "redirect" not in config:
        errs["redirect"] = "Missing required redirect configuration object"
    else:
        redirect, redirect_errs = config["redirect"], {}

        # Make sure method is present and is one of 'http' or 'https'
        if "method" not in redirect:
            redirect_errs["method"] = "Missing required 'http' or 'https' field"
        elif redirect["method"] not in ("http", "https"):
            redirect_errs["method"] = "Must be one of: 'http', 'https'"

        # Make sure host is present and is a string
        if "host" not in redirect:
            redirect_errs["host"] = "Missing required field"
        elif not isinstance(redirect["host"], str):
            redirect_errs["host"] = "Not a valid string"

        # Make sure port is present and is an integer
        if "port" not in redirect:
            redirect_errs["port"] = "Missing required field"
        elif not isinstance(redirect["port"], int):
            redirect_errs["port"] = "Not a valid integer"

        # Make sure path is present and is a string
        if "path" not in redirect:
            redirect_errs["path"] = "Missing required field"
        elif not isinstance(redirect["path"], str):
            redirect_errs["path"] = "Not a valid string"

    if redirect_errs:
        errs["redirect"] = redirect_errs

    return errs or None

def fetch_new_token(config, crypt, no_browser = False):
    app, cache = build_msal_app(config)
    state = str(uuid.uuid4())

    redirect_path = config["redirect"]["path"]
    # Remove / at the end if present, and path is not just /
    if redirect_path != "/" and redirect_path[-1] == "/":
        redirect_path = redirect_path[:-1]

    redirect_uri = (
        config["redirect"]["method"]
        + "://"
        + config["redirect"]["host"]
        + ":"
        + str(config["redirect"]["port"])
        + redirect_path
    )
    auth_url = app.get_authorization_request_url(
        config['scopes'],
        state=state,
        redirect_uri=redirect_uri
    )
    wsgi_app = WSGIRedirectionApp(SUCCESS_MESSAGE)
    http_server = simple_server.make_server(
        config["redirect"]["host"],
        config["redirect"]["port"],
        wsgi_app,
        handler_class=WSGIRequestHandler
    )
    if config["redirect"]["method"] == "https":
        http_server.socket = ssl_context().wrap_socket(http_server.socket, server_side=True)

    if no_browser:
        print("Please navigate to this url: " + auth_url)
    else:
        webbrowser.open(auth_url, new=2, autoraise=True)

    http_server.handle_request()
    auth_response = wsgi_app.last_request_uri
    http_server.server_close()
    parsed_auth_response = parse_qs(auth_response)

    code_key = (
        "http://"
        + config["redirect"]["host"]
        + ":"
        + str(config["redirect"]["port"])
        + "/"
        + "?code"
    )
    if code_key not in parsed_auth_response:
        _LOGGER.error(f"Could not find code in auth response: {parsed_auth_response}")
        return

    auth_code = parsed_auth_response[code_key]
    result = app.acquire_token_by_authorization_code(
        auth_code,
        scopes=config['scopes'],
        redirect_uri=redirect_uri
    )
    if result.get("access_token") is None:
        _LOGGER.error(f"Something went wrong during authorization: {result}")
        return

    return app, cache, result["access_token"]

def fetch_token_from_cache(config, cache):
    app, _ = build_msal_app(config, cache)
    accounts = app.get_accounts()
    if not accounts:
        _LOGGER.error("No accounts associated with token in cache")
        return

    result = app.acquire_token_silent(config["scopes"], account=accounts[0])
    if result and (token := result.get("access_token")):
        return app, token

    _LOGGER.info("Failed to retrive new access token silently")

def load_token_cache(crypt):
    if not os.path.exists(credentials_file):
        return None

    token = open(credentials_file, "r").read()
    if crypt:
        gpg = crypt["gpg"]
        token = str(gpg.decrypt(token))

    cache = msal.SerializableTokenCache()
    try:
        cache.deserialize(json.loads(token))
    except:
        _LOGGER.exception("Not a valid json file or it is ecrypted. Maybe add/remove the -e arugment?")
        sys.exit(1)

    return cache

# Encode the xoauth 2 message based on:
# https://docs.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth#sasl-xoauth2
def encode_xoauth2(username, token):
    C_A = b'\x01'
    user = ("user=" + username).encode("ascii")
    btoken = ("auth=Bearer " + token).encode("ascii")
    xoauth2_bytes = user + C_A + btoken + C_A + C_A
    return base64.b64encode(xoauth2_bytes).decode("utf-8")

def main(*args):
    args = parser.parse_args(args or None)

    crypt = None
    if args.encrypt_using_fingerprint:
        gpg_args = {"gnupghome": args.gpg_home} if args.gpg_home else {}
        gpg = gnupg.GPG(**gpg_args)
        crypt = {"gpg" : gpg, "fingerprint": args.encrypt_using_fingerprint}

    token = None
    cache = load_token_cache(crypt)
    config = load_config()

    # Load token using cache?
    if cache is not None:
        if success := fetch_token_from_cache(config, cache):
            app, token = success

    # No cache or cache lookup failed? → Grab new token
    if token is None:
        if success := fetch_new_token(config, crypt, args.no_browser):
            app, cache, token = success

    # If we still have not obtained a token by this point, something is wrong
    if token is None:
        _LOGGER.error("Something went wrong!")
        sys.exit(1)

    if not args.encode_xoauth2:
        print(token)
    else:
        accounts = app.get_accounts()
        if len(accounts) < 0:
            _LOGGER.error("Unable to encode xoauth2 message: no accounts found")
        elif accounts[0].get("username") is None:
            _LOGGER.error("Unable to encode xoauth2 message: missing account username")
        else:
            username = accounts[0]["username"]
            print(encode_xoauth2(username, token))

    if cache.has_state_changed and crypt is not None:
        state = json.dumps(cache.serialize())
        gpg = crypt["gpg"]
        fingerprint = crypt["fingerprint"]
        encrypted = str(gpg.encrypt(state, fingerprint, armor=False))
        open(credentials_file, "w").write(encrypted)


if __name__ == "__main__":
    main()
